PORTNAME=	extrace
DISTVERSION=	0.0
PORTREVISION=	1
CATEGORIES=	sysutils

MAINTAINER=	leah@vuxu.org
COMMENT=	Trace exec() calls system-wide
WWW=		https://github.com/leahneukirchen/extrace-freebsd

LICENSE=	CC0-1.0

USES=		uidfix
USE_GITHUB=	yes
GH_TUPLE=	leahneukirchen:extrace-freebsd:54be20a68a29aac75c881abdd08ad0abc5cf0cf3

.include <bsd.port.mk>
